blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ GitHub Discussions
    url: https://github.com/techsquidtv/hermes/discussions
    about: For questions and general discussions
  - name: ðŸ“– Documentation
    url: https://github.com/techsquidtv/hermes/tree/main/docs
    about: Check the documentation for guides and answers
